import type { User, Project, Transaction, BuybackRequest, Complaint, AdminNote, PortfolioItem } from './types';

export const mockUsers: User[] = [
  {
    id: 'u1',
    email: 'admin@tokenbiz.io',
    role: 'ADMIN',
    verificationStatus: 'verified',
    firstName: 'Platform',
    lastName: 'Admin',
    createdAt: '2025-01-15T10:00:00Z',
  },
  {
    id: 'u2',
    email: 'john@greenenergy.com',
    role: 'BUSINESS',
    verificationStatus: 'verified',
    firstName: 'John',
    lastName: 'Mitchell',
    phone: '+1-555-0102',
    representativePosition: 'CEO',
    legalEntityName: 'Green Energy Corp',
    countryOfIncorporation: 'United States',
    projectName: 'Green Energy Token',
    projectDescription: 'Tokenized renewable energy infrastructure investments',
    createdAt: '2025-02-01T10:00:00Z',
  },
  {
    id: 'u3',
    email: 'sarah@realtoken.io',
    role: 'BUSINESS',
    verificationStatus: 'under_review',
    firstName: 'Sarah',
    lastName: 'Chen',
    phone: '+65-9123-4567',
    representativePosition: 'CFO',
    legalEntityName: 'RealToken Asia Pte Ltd',
    countryOfIncorporation: 'Singapore',
    projectName: 'Asia Real Estate Fund',
    projectDescription: 'Tokenized commercial real estate across Southeast Asia',
    createdAt: '2025-03-10T10:00:00Z',
  },
  {
    id: 'u4',
    email: 'mike@example.com',
    role: 'INDIVIDUAL',
    verificationStatus: 'under_review',
    firstName: 'Mike',
    lastName: 'Rodriguez',
    phone: '+1-555-0199',
    citizenship: 'Mexico',
    projectDescription: 'Agricultural supply chain tokenization platform',
    createdAt: '2025-03-20T10:00:00Z',
  },
  {
    id: 'u5',
    email: 'alice@investor.com',
    role: 'BUYER',
    verificationStatus: 'verified',
    firstName: 'Alice',
    lastName: 'Thompson',
    phone: '+44-20-7123-4567',
    citizenship: 'United Kingdom',
    createdAt: '2025-04-01T10:00:00Z',
  },
  {
    id: 'u6',
    email: 'blocked@example.com',
    role: 'BUSINESS',
    verificationStatus: 'blocked',
    firstName: 'Robert',
    lastName: 'Fraud',
    phone: '+1-555-0000',
    representativePosition: 'Director',
    legalEntityName: 'Suspicious LLC',
    countryOfIncorporation: 'Panama',
    projectName: 'Definitely Legit Token',
    projectDescription: 'Trust us',
    createdAt: '2025-04-05T10:00:00Z',
  },
];

export const mockProjects: Project[] = [
  {
    id: 'p1',
    userId: 'u2',
    name: 'Green Energy Token',
    description: 'Invest in a portfolio of solar and wind farms across North America. Each token represents fractional ownership in renewable energy infrastructure generating consistent returns through power purchase agreements.',
    profitabilityStrategy: 'Revenue from long-term power purchase agreements (PPAs) with utilities. Expected annual yield of 8-12% distributed quarterly. Carbon credit sales provide additional upside.',
    tokenAddress: '7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU',
    tokenSymbol: 'GREN',
    totalSupply: 1000000,
    availableSupply: 650000,
    priceUsd: 2.50,
    createdAt: '2025-02-15T10:00:00Z',
    issuerName: 'Green Energy Corp',
    issuerVerified: 'verified',
  },
  {
    id: 'p2',
    userId: 'u3',
    name: 'Asia Real Estate Fund',
    description: 'Diversified exposure to premium commercial properties across Singapore, Bangkok, and Ho Chi Minh City. Institutional-grade real estate accessible through tokenized fractional ownership.',
    profitabilityStrategy: 'Rental income from Class A office buildings and retail spaces. Target NAV appreciation of 5-8% annually plus 4-6% rental yield. Properties managed by CBRE.',
    tokenAddress: '9xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgBsV',
    tokenSymbol: 'AREF',
    totalSupply: 5000000,
    availableSupply: 3200000,
    priceUsd: 1.00,
    createdAt: '2025-03-20T10:00:00Z',
    issuerName: 'RealToken Asia Pte Ltd',
    issuerVerified: 'under_review',
  },
  {
    id: 'p3',
    userId: 'u2',
    name: 'Carbon Credit Index',
    description: 'A tokenized index tracking verified carbon credits from reforestation, methane capture, and renewable energy projects. Aligned with Verra and Gold Standard certifications.',
    profitabilityStrategy: 'Appreciation driven by increasing global carbon pricing. EU ETS prices have risen 300% in 5 years. Tokens are backed 1:1 by verified carbon credits.',
    tokenAddress: '5xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgCsW',
    tokenSymbol: 'CARB',
    totalSupply: 2000000,
    availableSupply: 1800000,
    priceUsd: 0.75,
    createdAt: '2025-04-01T10:00:00Z',
    issuerName: 'Green Energy Corp',
    issuerVerified: 'verified',
  },
];

export const mockTransactions: Transaction[] = [
  {
    id: 't1',
    buyerId: 'u5',
    projectId: 'p1',
    amount: 1000,
    priceAtPurchase: 2.50,
    txHash: '4zJ8Kz...a9Xm',
    type: 'BUY',
    createdAt: '2025-04-10T14:30:00Z',
  },
  {
    id: 't2',
    buyerId: 'u5',
    projectId: 'p2',
    amount: 5000,
    priceAtPurchase: 1.00,
    txHash: '7bR3Lw...c2Yn',
    type: 'BUY',
    createdAt: '2025-04-12T09:15:00Z',
  },
  {
    id: 't3',
    buyerId: 'u5',
    projectId: 'p1',
    amount: 250,
    priceAtPurchase: 2.50,
    txHash: '2pQ9Nx...d4Zo',
    type: 'CLAIM',
    createdAt: '2025-04-15T16:00:00Z',
  },
];

export const mockBuybacks: BuybackRequest[] = [
  {
    id: 'bb1',
    buyerId: 'u5',
    buyerName: 'Alice Thompson',
    projectId: 'p1',
    tokenAmount: 200,
    status: 'PENDING',
    createdAt: '2025-04-18T11:00:00Z',
  },
];

export const mockComplaints: Complaint[] = [
  {
    id: 'c1',
    submitterId: 'u5',
    submitterName: 'Alice Thompson',
    submitterEmail: 'alice@investor.com',
    projectId: 'p1',
    text: 'Quarterly dividend payment was delayed by 15 days without any communication from the issuer.',
    status: 'OPEN',
    createdAt: '2025-04-16T08:00:00Z',
  },
];

export const mockAdminNotes: AdminNote[] = [
  {
    id: 'an1',
    adminId: 'u1',
    targetUserId: 'u6',
    note: 'Flagged for suspicious activity. Documents appear forged. Blocking account pending investigation.',
    createdAt: '2025-04-06T10:00:00Z',
  },
];

export const mockPortfolio: PortfolioItem[] = [
  {
    projectId: 'p1',
    projectName: 'Green Energy Token',
    tokenSymbol: 'GREN',
    amount: 1000,
    currentPrice: 2.50,
    totalValue: 2500,
    issuerVerified: 'verified',
    description: 'Tokenized renewable energy infrastructure investments',
  },
  {
    projectId: 'p2',
    projectName: 'Asia Real Estate Fund',
    tokenSymbol: 'AREF',
    amount: 5000,
    currentPrice: 1.00,
    totalValue: 5000,
    issuerVerified: 'under_review',
    description: 'Tokenized commercial real estate across Southeast Asia',
  },
];